//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetGenerator.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set
    {
        public int Id { get; set; }
        public int SetListId { get; set; }
        public int Number { get; set; }
        public int SongId { get; set; }
        public int Sequence { get; set; }
        public long UserCreateId { get; set; }
        public long UserUpdateId { get; set; }
    
        public virtual SetList SetList { get; set; }
        public virtual Song Song { get; set; }
    }
}
