//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetGenerator.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongMemberInstrument
    {
        public int BandId { get; set; }
        public int SongId { get; set; }
        public int MemberId { get; set; }
        public Nullable<int> InstrumentId { get; set; }
    
        public virtual Band Band { get; set; }
        public virtual Instrument Instrument { get; set; }
        public virtual Member Member { get; set; }
        public virtual Song Song { get; set; }
    }
}
