//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetGenerator.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetSong
    {
        public int Id { get; set; }
        public int SetListId { get; set; }
        public int SetNumber { get; set; }
        public int SongId { get; set; }
        public int Sequence { get; set; }
    
        public virtual Setlist Setlist { get; set; }
    }
}
