//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetGenerator.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int Id { get; set; }
        public int BandId { get; set; }
        public string Title { get; set; }
        public string Composer { get; set; }
        public Nullable<int> SingerId { get; set; }
        public int KeyId { get; set; }
        public bool NeverClose { get; set; }
        public bool NeverOpen { get; set; }
        public int GenreId { get; set; }
        public int TempoId { get; set; }
        public bool IsDisabled { get; set; }
        public long UserCreateId { get; set; }
        public long UserUpdateId { get; set; }
        public System.DateTime DateCreate { get; set; }
        public System.DateTime DateUpdate { get; set; }
    
        public virtual Band Band { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Key Key { get; set; }
        public virtual Member Member { get; set; }
        public virtual Tempo Tempo { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
