//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetGenerator.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreferenceTableColumn
    {
        public int Id { get; set; }
        public long UserId { get; set; }
        public int TableColumnId { get; set; }
        public bool IsVisible { get; set; }
    
        public virtual TableColumn TableColumn { get; set; }
        public virtual User User { get; set; }
    }
}
