//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetGenerator.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSongMemberInstrumentMatch
    {
        public Nullable<long> Id { get; set; }
        public int BandId { get; set; }
        public int SongId { get; set; }
        public int MatchingSongId { get; set; }
    }
}
